name: build pm2 image

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build image job1
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                publish: true
                platform: linux/amd64,linux/arm64
                tag: ${{ github.ref_name }}
                imageName: ${{ secrets.DOCKER_IMAGE_NAME }}
                dockerUser: ${{ secrets.DOCKER_HUB_USER_NAME }}
                dockerPassword: ${{ secrets.DOCKER_HUB_USER_PASSWORD }}
