name: build pm2 image

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build image job1
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                publish: true
                imageName: ${{YOUR_IMAGE_NAME_HERE}}
                dockerUser: ${{YOUR_USER_HERE}}
                dockerPassword: ${{YOUR_PASSWORD_HERE}}
